name: pr-build

on:
  pull_request:

jobs:
  func-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: cpanato/faas-cli-installer@v1.0.0

      - name: Pull template
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: template store pull golang-http

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build functions
        run: faas-cli build -f functions-stack.yml
